const assistantData = {
  en: {
    welcome: 'Hi! I’m the local Sani website guide. Ask me about Ehsan’s services, projects, experience or how to get in touch.',
    placeholder: 'Ask about services, projects…', privacy: 'Runs locally · No messages are stored', suggestions: ['Services', 'Projects', 'Experience', 'Contact'],
    answers: {
      services: 'Ehsan offers business websites, full-stack web applications, AI-assisted tools, automation, redesigns and technical support through Sani Studio.',
      projects: 'Featured work includes the Saaren Pizza & Kebab ordering system and a Central Finland tourism platform with AI-assisted discovery.',
      experience: 'Ehsan is a full-stack software developer with previous experience as a Project Specialist. His Portfolio contains his résumé, career history and selected work.',
      contact: 'You can email Ehsan at ehsanmohajer.fi@gmail.com or use the callback form on this page.',
      studio: 'For a website, digital product or a new business idea, visit Sani Studio.',
      portfolio: 'For Ehsan’s résumé, experience and previous work, visit his Portfolio.',
      languages: 'Ehsan’s services and this website are available in English, Finnish and Persian.',
      fallback: 'I don’t have a prepared answer for that yet. You can ask about services, projects, experience, languages or contact Ehsan directly.'
    }, links: { services:['Visit Sani Studio','https://sanistudio.vercel.app/'], projects:['View projects','https://saniportfolio.vercel.app/projects'], experience:['View Portfolio','https://saniportfolio.vercel.app/'], contact:['Go to contact form','#contact'] }
  },
  fi: {
    welcome: 'Hei! Olen paikallinen Sani-sivusto-opas. Kysy Ehsanin palveluista, projekteista, kokemuksesta tai yhteydenotosta.',
    placeholder: 'Kysy palveluista tai projekteista…', privacy: 'Toimii paikallisesti · Viestejä ei tallenneta', suggestions: ['Palvelut', 'Projektit', 'Kokemus', 'Yhteystiedot'],
    answers: { services:'Ehsan tarjoaa yrityssivustoja, full-stack-verkkosovelluksia, tekoälytyökaluja, automaatiota, uudistuksia ja teknistä tukea Sani Studion kautta.', projects:'Valittuihin töihin kuuluvat Saaren Pizza & Kebab -tilausjärjestelmä ja Keski-Suomen tekoälyavusteinen matkailualusta.', experience:'Ehsan on full-stack-ohjelmistokehittäjä, jolla on aiempaa kokemusta Project Specialist -tehtävästä. Portfolio sisältää CV:n, urahistorian ja valitut työt.', contact:'Voit lähettää sähköpostia osoitteeseen ehsanmohajer.fi@gmail.com tai käyttää tämän sivun yhteydenottolomaketta.', studio:'Kun tarvitset verkkosivuston, digitaalisen tuotteen tai haluat kehittää ideaa, tutustu Sani Studioon.', portfolio:'Ehsanin CV, kokemus ja aiemmat työt löytyvät Portfoliosta.', languages:'Palvelut ja tämä sivusto ovat saatavilla englanniksi, suomeksi ja persiaksi.', fallback:'Minulla ei ole vielä valmista vastausta tähän. Kysy palveluista, projekteista, kokemuksesta tai ota suoraan yhteyttä Ehsaniin.' },
    links:{services:['Sani Studioon','https://sanistudio.vercel.app/'],projects:['Katso projektit','https://saniportfolio.vercel.app/projects'],experience:['Katso Portfolio','https://saniportfolio.vercel.app/'],contact:['Yhteydenottolomake','#contact']}
  },
  fa: {
    welcome: 'سلام! من راهنمای محلی وب‌سایت سانی هستم. درباره خدمات، پروژه‌ها، تجربه کاری احسان یا راه‌های تماس سؤال کنید.',
    placeholder: 'درباره خدمات یا پروژه‌ها بپرسید…', privacy: 'اجرای محلی · پیام‌ها ذخیره نمی‌شوند', suggestions: ['خدمات', 'پروژه‌ها', 'تجربه کاری', 'تماس'],
    answers:{services:'احسان از طریق استودیو سانی خدمات طراحی وب‌سایت، اپلیکیشن فول‌استک، ابزارهای هوش مصنوعی، اتوماسیون، بازطراحی و پشتیبانی فنی ارائه می‌دهد.',projects:'پروژه‌های منتخب شامل سیستم سفارش Saaren Pizza & Kebab و پلتفرم گردشگری فنلاند مرکزی با جست‌وجوی مبتنی بر هوش مصنوعی است.',experience:'احسان توسعه‌دهنده فول‌استک است و سابقه فعالیت به‌عنوان Project Specialist دارد. رزومه، مسیر شغلی و نمونه‌کارها در پورتفولیو قرار دارند.',contact:'می‌توانید به ehsanmohajer.fi@gmail.com ایمیل بزنید یا فرم درخواست تماس همین صفحه را تکمیل کنید.',studio:'برای طراحی وب‌سایت، محصول دیجیتال یا توسعه یک ایده جدید به استودیو سانی مراجعه کنید.',portfolio:'برای مشاهده رزومه، تجربه کاری و پروژه‌های احسان، پورتفولیو را ببینید.',languages:'خدمات احسان و این وب‌سایت به زبان‌های انگلیسی، فنلاندی و فارسی ارائه می‌شوند.',fallback:'هنوز پاسخ آماده‌ای برای این سؤال ندارم. می‌توانید درباره خدمات، پروژه‌ها، تجربه کاری یا تماس با احسان سؤال کنید.'},
    links:{services:['مشاهده استودیو سانی','https://sanistudio.vercel.app/'],projects:['مشاهده پروژه‌ها','https://saniportfolio.vercel.app/projects'],experience:['مشاهده پورتفولیو','https://saniportfolio.vercel.app/'],contact:['رفتن به فرم تماس','#contact']}
  }
};

const launcher=document.getElementById('assistant-launcher'),panel=document.getElementById('assistant-panel'),messages=document.getElementById('assistant-messages'),suggestions=document.getElementById('assistant-suggestions'),assistantInput=document.getElementById('assistant-input');
let assistantLanguage=document.documentElement.lang in assistantData?document.documentElement.lang:'en';
function addMessage(text,type,link){const el=document.createElement('div');el.className=`assistant-message ${type}`;el.textContent=text;if(link){const a=document.createElement('a');a.href=link[1];a.textContent=link[0]+' ↗';if(link[1].startsWith('http')){a.target='_blank';a.rel='noopener'}el.appendChild(document.createElement('br'));el.appendChild(a)}messages.appendChild(el);messages.scrollTop=messages.scrollHeight}
function assistantTopic(question){const q=question.toLowerCase();if(/service|palvel|خدمات|website|verkkos|وب.?سایت|design/.test(q))return'services';if(/project|projek|پروژه|saaren|tourism|matkail|گردش/.test(q))return'projects';if(/experience|resume|cv|kokemus|تجربه|رزومه|specialist/.test(q))return'experience';if(/contact|email|phone|yhtey|تماس|ایمیل/.test(q))return'contact';if(/studio|استودیو/.test(q))return'studio';if(/portfolio|پورتفولیو/.test(q))return'portfolio';if(/language|kiel|زبان/.test(q))return'languages';return'fallback'}
function renderAssistant(reset=false){assistantLanguage=document.documentElement.lang in assistantData?document.documentElement.lang:'en';const d=assistantData[assistantLanguage];assistantInput.placeholder=d.placeholder;document.querySelector('.assistant-privacy').textContent=d.privacy;suggestions.innerHTML='';d.suggestions.forEach(label=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>answerQuestion(label);suggestions.appendChild(b)});if(reset){messages.innerHTML='';addMessage(d.welcome,'bot')}}
function answerQuestion(question){const d=assistantData[assistantLanguage];addMessage(question,'user');const topic=assistantTopic(question);setTimeout(()=>addMessage(d.answers[topic],'bot',d.links[topic]),180)}
launcher.addEventListener('click',()=>{const open=panel.hidden;panel.hidden=!open;launcher.setAttribute('aria-expanded',String(open));if(open){renderAssistant(messages.children.length===0);assistantInput.focus()}});document.getElementById('assistant-close').addEventListener('click',()=>{panel.hidden=true;launcher.setAttribute('aria-expanded','false')});document.getElementById('assistant-form').addEventListener('submit',e=>{e.preventDefault();const q=assistantInput.value.trim();if(q){answerQuestion(q);assistantInput.value=''}});document.querySelectorAll('.language-select').forEach(select=>select.addEventListener('change',()=>renderAssistant(true)));
const backToTop=document.getElementById('back-to-top');window.addEventListener('scroll',()=>backToTop.classList.toggle('visible',window.scrollY>500),{passive:true});backToTop.addEventListener('click',()=>window.scrollTo({top:0,behavior:reduceMotion?'auto':'smooth'}));
