const contactThemeButtons=document.querySelectorAll('.theme-toggle');
function setContactTheme(theme){const selected=theme==='light'?'light':'dark';document.documentElement.dataset.theme=selected;contactThemeButtons.forEach(button=>{button.querySelector('.theme-icon').textContent=selected==='dark'?'☼':'☾';button.setAttribute('aria-label',selected==='dark'?'Switch to light mode':'Switch to dark mode')});localStorage.setItem('preferredTheme',selected)}
setContactTheme(localStorage.getItem('preferredTheme')||(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'));contactThemeButtons.forEach(button=>button.addEventListener('click',()=>setContactTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')));
const contactCopy={en:{intro:'Sani Portal is the central point for connecting with Ehsan Mohajer. Tell me what you’re building, improving or exploring, and I’ll respond with the most relevant next step. Website and product enquiries are handled through Sani Studio; professional background and previous experience are available in Sani Portfolio.',title:'Let’s find the right<br><span>way forward.</span>',formTitle:'Tell me about<br>your needs.'},fi:{intro:'Sani Portal on keskitetty yhteyspiste Ehsan Mohajeriin. Kerro, mitä olet rakentamassa, kehittämässä tai tutkimassa, niin vastaan sopivimmalla seuraavalla askeleella. Verkkosivusto- ja tuotekyselyt hoidetaan Sani Studion kautta, ja työkokemus sekä aiempi ura löytyvät Sani Portfoliosta.',title:'Löydetään oikea<br><span>suunta eteenpäin.</span>',formTitle:'Kerro minulle<br>tarpeestasi.'},fa:{intro:'Sani Portal نقطه اصلی ارتباط با احسان مهاجر است. درباره چیزی که می‌خواهید بسازید، بهبود دهید یا بررسی کنید توضیح دهید تا مناسب‌ترین مسیر بعدی را پیشنهاد کنم. درخواست‌های طراحی وب و محصول از طریق Sani Studio و سوابق حرفه‌ای از طریق Sani Portfolio ارائه می‌شوند.',title:'بیایید بهترین<br><span>مسیر را پیدا کنیم.</span>',formTitle:'درباره نیازتان<br>توضیح دهید.'}};
const contactUi={en:{'#enquiry-title':'Tell me about<br>your needs.','label[for="first-name"]':'First name <b>*</b>','label[for="last-name"]':'Last name','label[for="business-email"]':'Business email <b>*</b>','label[for="company-name"]':'Company or organisation <b>*</b>','label[for="job-title"]':'Your role <b>*</b>','label[for="country"]':'Country <b>*</b>','label[for="interest"]':'Primary area of interest <b>*</b>','label[for="help"]':'How can I help?','label[for="referral"]':'How did you hear about Sani Portal?','.portal-submit':'Prepare enquiry email <span>↗</span>'},fi:{'#enquiry-title':'Kerro minulle<br>tarpeestasi.','label[for="first-name"]':'Etunimi <b>*</b>','label[for="last-name"]':'Sukunimi','label[for="business-email"]':'Työsähköposti <b>*</b>','label[for="company-name"]':'Yritys tai organisaatio <b>*</b>','label[for="job-title"]':'Roolisi <b>*</b>','label[for="country"]':'Maa <b>*</b>','label[for="interest"]':'Ensisijainen kiinnostuksen kohde <b>*</b>','label[for="help"]':'Miten voin auttaa?','label[for="referral"]':'Miten kuulit Sani Portalista?','.portal-submit':'Valmistele sähköposti <span>↗</span>'},fa:{'#enquiry-title':'درباره نیازتان<br>توضیح دهید.','label[for="first-name"]':'نام <b>*</b>','label[for="last-name"]':'نام خانوادگی','label[for="business-email"]':'ایمیل کاری <b>*</b>','label[for="company-name"]':'شرکت یا سازمان <b>*</b>','label[for="job-title"]':'سمت شما <b>*</b>','label[for="country"]':'کشور <b>*</b>','label[for="interest"]':'حوزه اصلی موردنظر <b>*</b>','label[for="help"]':'چطور می‌توانم کمک کنم؟','label[for="referral"]':'چطور با Sani Portal آشنا شدید؟','.portal-submit':'آماده‌سازی ایمیل درخواست <span>↗</span>'}};
function applyContactUi(language){Object.entries(contactUi[language]).forEach(([selector,html])=>{const element=document.querySelector(selector);if(element)element.innerHTML=html})}
function setContactLanguage(lang){const selected=contactCopy[lang]?lang:'en';document.documentElement.lang=selected;document.documentElement.dir=selected==='fa'?'rtl':'ltr';document.querySelectorAll('.language-select').forEach(select=>select.value=selected);document.querySelector('.contact-hero h1').innerHTML=contactCopy[selected].title;document.querySelector('.contact-lead').textContent=contactCopy[selected].intro;applyContactUi(selected);localStorage.setItem('preferredLanguage',selected)}
document.querySelectorAll('.language-select').forEach(select=>select.addEventListener('change',event=>setContactLanguage(event.target.value)));setContactLanguage(localStorage.getItem('preferredLanguage')||(navigator.language.startsWith('fa')?'fa':navigator.language.startsWith('fi')?'fi':'en'));
document.getElementById('contact-year').textContent=new Date().getFullYear();document.getElementById('portal-contact-form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const subject=`Sani Portal enquiry: ${data.get('interest')} — ${data.get('company')}`;const body=`Name: ${data.get('firstName')} ${data.get('lastName')}\nBusiness email: ${data.get('email')}\nCompany: ${data.get('company')}\nRole: ${data.get('role')}\nCountry: ${data.get('country')}\nInterest: ${data.get('interest')}\nReferral: ${data.get('referral')}\n\nHow can I help?\n${data.get('message')||'Not provided'}`;location.href=`mailto:ehsanmohajer.fi@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`});

// Subpages use one consistent light layout and inherit language from Sani Portal.
document.documentElement.dataset.theme=localStorage.getItem('preferredTheme')||(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark');
const subpageStyle=document.createElement('link');subpageStyle.rel='stylesheet';subpageStyle.href='subpage.css';document.head.appendChild(subpageStyle);const themeStyle=document.createElement('link');themeStyle.rel='stylesheet';themeStyle.href='subpage-theme.css';document.head.appendChild(themeStyle);
const contactNavNames={en:['Portal','Studio','Portfolio','Blog','About','Contact'],fi:['Portaali','Studio','Portfolio','Blogi','Minusta','Yhteystiedot'],fa:['پورتال','استودیو','پورتفولیو','وبلاگ','درباره من','تماس']};
const contactNavLinks=['index.html','https://sanistudio.vercel.app/','https://saniportfolio.vercel.app/','blog.html','about.html','contact.html'];
const contactLanguage=document.documentElement.lang;
document.querySelector('.contact-header nav').innerHTML=contactNavLinks.map((href,index)=>`<a href="${href}"${index===1||index===2?' target="_blank" rel="noopener"':''}${index===5?' aria-current="page"':''}>${contactNavNames[contactLanguage][index]}</a>`).join('');
const contactTitles={en:'Contact',fi:'Yhteystiedot',fa:'تماس'};const contactBrand=document.querySelector('.contact-header .brand');contactBrand.innerHTML=`<span class="subpage-title">${contactTitles[contactLanguage]}</span>`;contactBrand.setAttribute('aria-label',contactTitles[contactLanguage]);
const contactExtra={fi:{'.enquiry-intro>p:nth-of-type(2)':'Tähdellä <b>*</b> merkityt kentät ovat pakollisia.','.direct-contact small':'SUORA YHTEYDENOTTO','.direct-contact span':'Jyväskylä, Suomi · Etätyö maailmanlaajuisesti','.consent span':'Hyväksyn, että Sani Portal käyttää antamiani tietoja tähän yhteydenottoon vastaamiseen. Tietoja ei myydä eikä käytetä asiaankuulumattomaan markkinointiin. <b>*</b>','.privacy-copy':'Voit pyytää tietojesi korjaamista tai poistamista milloin tahansa. Lisätietoja löydät <a href="privacy.html">tietosuojakäytännöstä</a>.','.submit-note':'APIa tai ulkoista lomakepalvelua ei käytetä. Sähköpostisovelluksesi avautuu valmiin viestin kanssa.'},fa:{'.enquiry-intro>p:nth-of-type(2)':'فیلدهای دارای علامت <b>*</b> الزامی هستند.','.direct-contact small':'تماس مستقیم','.direct-contact span':'یواسکولا، فنلاند · همکاری آنلاین در سراسر جهان','.consent span':'موافقت می‌کنم Sani Portal از اطلاعات ارائه‌شده برای پاسخ به این درخواست استفاده کند. اطلاعات من فروخته یا برای بازاریابی نامرتبط استفاده نخواهد شد. <b>*</b>','.privacy-copy':'هر زمان می‌توانید اصلاح یا حذف اطلاعات تماس خود را درخواست کنید. برای جزئیات، <a href="privacy.html">سیاست حفظ حریم خصوصی</a> را مطالعه کنید.','.submit-note':'هیچ API یا سرویس فرم خارجی استفاده نمی‌شود. برنامه ایمیل شما با پیام آماده باز خواهد شد.'}};
if(contactLanguage!=='en')Object.entries(contactExtra[contactLanguage]).forEach(([selector,html])=>{const element=document.querySelector(selector);if(element)element.innerHTML=html});
const optionCopy={fi:{country:['Valitse','Suomi','Ruotsi','Norja','Tanska','Saksa','Yhdistynyt kuningaskunta','Muu'],interest:['Valitse','Yrityksen verkkosivusto','Verkkosivuston uudistus','Full-stack-verkkosovellus','Tekoälytyökalut ja automaatio','Digitaalisen tuotteen konsultointi','Ylläpito ja tekninen tuki','Muu'],referral:['Valitse','Google tai muu hakukone','LinkedIn','Suositus','Paikallinen yritysverkosto','Sani Studio','Sani Portfolio','Muu']},fa:{country:['انتخاب کنید','فنلاند','سوئد','نروژ','دانمارک','آلمان','بریتانیا','سایر'],interest:['انتخاب کنید','وب‌سایت تجاری','بازطراحی وب‌سایت','برنامه وب فول‌استک','ابزارهای هوش مصنوعی و اتوماسیون','مشاوره محصول دیجیتال','نگهداری و پشتیبانی فنی','سایر'],referral:['انتخاب کنید','گوگل یا موتور جست‌وجو','لینکدین','معرفی دیگران','شبکه کسب‌وکار محلی','Sani Studio','Sani Portfolio','سایر']}};
if(contactLanguage!=='en'){['country','interest','referral'].forEach(id=>document.querySelectorAll(`#${id} option`).forEach((option,index)=>{option.textContent=optionCopy[contactLanguage][id][index]}))}
const contactTop=document.createElement('button');contactTop.className='subpage-top';contactTop.type='button';contactTop.setAttribute('aria-label','Back to top');contactTop.textContent='↑';document.body.appendChild(contactTop);addEventListener('scroll',()=>contactTop.classList.toggle('visible',scrollY>500),{passive:true});contactTop.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
